name: "Build and test"

on:
  push:
    branches:
      - main # run for pushes to the main branch. other branches need to create a PR if they want testing.
  pull_request:
  workflow_dispatch:


jobs:
  build-and-test:
    name: "Build and Test"
    strategy:
      # run all combinations of the matrix even if one combination fails.
      fail-fast: false
      matrix:
        rust_release:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - run: rustup update ${{ matrix.rust_release }} && rustup default ${{ matrix.rust_release }}

      - run: cargo build --verbose
      - run: cargo test --verbose

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-targets -- -D warnings
